package com.lzx.mapper;

import com.lzx.entity.DisAssociation;
import com.lzx.entity.DisAssociationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisAssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    long countByExample(DisAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    int deleteByExample(DisAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    int insert(DisAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    int insertSelective(DisAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    List<DisAssociation> selectByExample(DisAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisAssociation record, @Param("example") DisAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisAssociation record, @Param("example") DisAssociationExample example);
}