package com.lzx.mapper;

import com.lzx.entity.DisCityArea;
import com.lzx.entity.DisCityAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisCityAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    long countByExample(DisCityAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    int deleteByExample(DisCityAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    int insert(DisCityArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    int insertSelective(DisCityArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    List<DisCityArea> selectByExample(DisCityAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    DisCityArea selectByPrimaryKey(String areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisCityArea record, @Param("example") DisCityAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisCityArea record, @Param("example") DisCityAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisCityArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisCityArea record);
}