package com.lzx.mapper;

import com.lzx.entity.DisCity;
import com.lzx.entity.DisCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    long countByExample(DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int deleteByExample(DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int insert(DisCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int insertSelective(DisCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    List<DisCity> selectByExample(DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    DisCity selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisCity record, @Param("example") DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisCity record, @Param("example") DisCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisCity record);
}