package com.lzx.mapper;

import com.lzx.entity.DisCustomer;
import com.lzx.entity.DisCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    long countByExample(DisCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    int deleteByExample(DisCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    int insert(DisCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    int insertSelective(DisCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    List<DisCustomer> selectByExample(DisCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    DisCustomer selectByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisCustomer record, @Param("example") DisCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisCustomer record, @Param("example") DisCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisCustomer record);
}