package com.lzx.mapper;

import com.lzx.entity.DisDeliveryRange;
import com.lzx.entity.DisDeliveryRangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisDeliveryRangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    long countByExample(DisDeliveryRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    int deleteByExample(DisDeliveryRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    int insert(DisDeliveryRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    int insertSelective(DisDeliveryRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    List<DisDeliveryRange> selectByExample(DisDeliveryRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    DisDeliveryRange selectByPrimaryKey(String rangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisDeliveryRange record, @Param("example") DisDeliveryRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisDeliveryRange record, @Param("example") DisDeliveryRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisDeliveryRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_range
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisDeliveryRange record);
}