package com.lzx.mapper;

import com.lzx.entity.DisDeliveryReceipt;
import com.lzx.entity.DisDeliveryReceiptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisDeliveryReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    long countByExample(DisDeliveryReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    int deleteByExample(DisDeliveryReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryReceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    int insert(DisDeliveryReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    int insertSelective(DisDeliveryReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    List<DisDeliveryReceipt> selectByExample(DisDeliveryReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    DisDeliveryReceipt selectByPrimaryKey(String deliveryReceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisDeliveryReceipt record, @Param("example") DisDeliveryReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisDeliveryReceipt record, @Param("example") DisDeliveryReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisDeliveryReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_receipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisDeliveryReceipt record);
}