package com.lzx.mapper;

import com.lzx.entity.DisDeliveryPlace;
import com.lzx.entity.DisDeliveryPlaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisDeliveryPlaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    long countByExample(DisDeliveryPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    int deleteByExample(DisDeliveryPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    int insert(DisDeliveryPlace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    int insertSelective(DisDeliveryPlace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    List<DisDeliveryPlace> selectByExample(DisDeliveryPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    DisDeliveryPlace selectByPrimaryKey(String depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisDeliveryPlace record, @Param("example") DisDeliveryPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisDeliveryPlace record, @Param("example") DisDeliveryPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisDeliveryPlace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_delivery_place
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisDeliveryPlace record);
}