package com.lzx.mapper;

import com.lzx.entity.DisManager;
import com.lzx.entity.DisManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    long countByExample(DisManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    int deleteByExample(DisManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    int insert(DisManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    int insertSelective(DisManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    List<DisManager> selectByExample(DisManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    DisManager selectByPrimaryKey(String managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisManager record, @Param("example") DisManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisManager record, @Param("example") DisManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisManager record);
}