package com.lzx.mapper;

import com.lzx.entity.DisRole;
import com.lzx.entity.DisRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    long countByExample(DisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    int deleteByExample(DisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    int insert(DisRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    int insertSelective(DisRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    List<DisRole> selectByExample(DisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    DisRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DisRole record, @Param("example") DisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DisRole record, @Param("example") DisRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisRole record);
}