package com.lzx.entity;

import java.util.ArrayList;
import java.util.List;

public class DisAssociationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public DisAssociationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrdOrderIdIsNull() {
            addCriterion("ord_order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdIsNotNull() {
            addCriterion("ord_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdEqualTo(String value) {
            addCriterion("ord_order_id =", value, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdNotEqualTo(String value) {
            addCriterion("ord_order_id <>", value, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdGreaterThan(String value) {
            addCriterion("ord_order_id >", value, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("ord_order_id >=", value, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdLessThan(String value) {
            addCriterion("ord_order_id <", value, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdLessThanOrEqualTo(String value) {
            addCriterion("ord_order_id <=", value, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdLike(String value) {
            addCriterion("ord_order_id like", value, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdNotLike(String value) {
            addCriterion("ord_order_id not like", value, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdIn(List<String> values) {
            addCriterion("ord_order_id in", values, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdNotIn(List<String> values) {
            addCriterion("ord_order_id not in", values, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdBetween(String value1, String value2) {
            addCriterion("ord_order_id between", value1, value2, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrdOrderIdNotBetween(String value1, String value2) {
            addCriterion("ord_order_id not between", value1, value2, "ordOrderId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdIsNull() {
            addCriterion("del_delivery_receipt_id is null");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdIsNotNull() {
            addCriterion("del_delivery_receipt_id is not null");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdEqualTo(String value) {
            addCriterion("del_delivery_receipt_id =", value, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdNotEqualTo(String value) {
            addCriterion("del_delivery_receipt_id <>", value, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdGreaterThan(String value) {
            addCriterion("del_delivery_receipt_id >", value, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdGreaterThanOrEqualTo(String value) {
            addCriterion("del_delivery_receipt_id >=", value, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdLessThan(String value) {
            addCriterion("del_delivery_receipt_id <", value, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdLessThanOrEqualTo(String value) {
            addCriterion("del_delivery_receipt_id <=", value, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdLike(String value) {
            addCriterion("del_delivery_receipt_id like", value, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdNotLike(String value) {
            addCriterion("del_delivery_receipt_id not like", value, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdIn(List<String> values) {
            addCriterion("del_delivery_receipt_id in", values, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdNotIn(List<String> values) {
            addCriterion("del_delivery_receipt_id not in", values, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdBetween(String value1, String value2) {
            addCriterion("del_delivery_receipt_id between", value1, value2, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDelDeliveryReceiptIdNotBetween(String value1, String value2) {
            addCriterion("del_delivery_receipt_id not between", value1, value2, "delDeliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdIsNull() {
            addCriterion("delivery_receipt_id is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdIsNotNull() {
            addCriterion("delivery_receipt_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdEqualTo(String value) {
            addCriterion("delivery_receipt_id =", value, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdNotEqualTo(String value) {
            addCriterion("delivery_receipt_id <>", value, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdGreaterThan(String value) {
            addCriterion("delivery_receipt_id >", value, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdGreaterThanOrEqualTo(String value) {
            addCriterion("delivery_receipt_id >=", value, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdLessThan(String value) {
            addCriterion("delivery_receipt_id <", value, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdLessThanOrEqualTo(String value) {
            addCriterion("delivery_receipt_id <=", value, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdLike(String value) {
            addCriterion("delivery_receipt_id like", value, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdNotLike(String value) {
            addCriterion("delivery_receipt_id not like", value, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdIn(List<String> values) {
            addCriterion("delivery_receipt_id in", values, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdNotIn(List<String> values) {
            addCriterion("delivery_receipt_id not in", values, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdBetween(String value1, String value2) {
            addCriterion("delivery_receipt_id between", value1, value2, "deliveryReceiptId");
            return (Criteria) this;
        }

        public Criteria andDeliveryReceiptIdNotBetween(String value1, String value2) {
            addCriterion("delivery_receipt_id not between", value1, value2, "deliveryReceiptId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_association
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_association
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}