package com.lzx.entity;

import java.util.Date;

public class DisCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.car_id
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.route_id
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.car_type
     *
     * @mbg.generated
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.car_orgin
     *
     * @mbg.generated
     */
    private String carOrgin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.car_prodate
     *
     * @mbg.generated
     */
    private Date carProdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.car_buytime
     *
     * @mbg.generated
     */
    private Date carBuytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.car_capacity
     *
     * @mbg.generated
     */
    private Integer carCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.car_state
     *
     * @mbg.generated
     */
    private Boolean carState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_car.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.car_id
     *
     * @return the value of dis_car.car_id
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.car_id
     *
     * @param carId the value for dis_car.car_id
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.route_id
     *
     * @return the value of dis_car.route_id
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.route_id
     *
     * @param routeId the value for dis_car.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.car_type
     *
     * @return the value of dis_car.car_type
     *
     * @mbg.generated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.car_type
     *
     * @param carType the value for dis_car.car_type
     *
     * @mbg.generated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.car_orgin
     *
     * @return the value of dis_car.car_orgin
     *
     * @mbg.generated
     */
    public String getCarOrgin() {
        return carOrgin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.car_orgin
     *
     * @param carOrgin the value for dis_car.car_orgin
     *
     * @mbg.generated
     */
    public void setCarOrgin(String carOrgin) {
        this.carOrgin = carOrgin == null ? null : carOrgin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.car_prodate
     *
     * @return the value of dis_car.car_prodate
     *
     * @mbg.generated
     */
    public Date getCarProdate() {
        return carProdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.car_prodate
     *
     * @param carProdate the value for dis_car.car_prodate
     *
     * @mbg.generated
     */
    public void setCarProdate(Date carProdate) {
        this.carProdate = carProdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.car_buytime
     *
     * @return the value of dis_car.car_buytime
     *
     * @mbg.generated
     */
    public Date getCarBuytime() {
        return carBuytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.car_buytime
     *
     * @param carBuytime the value for dis_car.car_buytime
     *
     * @mbg.generated
     */
    public void setCarBuytime(Date carBuytime) {
        this.carBuytime = carBuytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.car_capacity
     *
     * @return the value of dis_car.car_capacity
     *
     * @mbg.generated
     */
    public Integer getCarCapacity() {
        return carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.car_capacity
     *
     * @param carCapacity the value for dis_car.car_capacity
     *
     * @mbg.generated
     */
    public void setCarCapacity(Integer carCapacity) {
        this.carCapacity = carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.car_state
     *
     * @return the value of dis_car.car_state
     *
     * @mbg.generated
     */
    public Boolean getCarState() {
        return carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.car_state
     *
     * @param carState the value for dis_car.car_state
     *
     * @mbg.generated
     */
    public void setCarState(Boolean carState) {
        this.carState = carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_car.comment
     *
     * @return the value of dis_car.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_car.comment
     *
     * @param comment the value for dis_car.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}