package com.lzx.entity;

public class DisDeliveryPlace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.dep_id
     *
     * @mbg.generated
     */
    private String depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.manager_id
     *
     * @mbg.generated
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.dep_name
     *
     * @mbg.generated
     */
    private String depName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.province_name
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.manager_name
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.dep_tel
     *
     * @mbg.generated
     */
    private String depTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.dep_addr
     *
     * @mbg.generated
     */
    private String depAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_place.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.dep_id
     *
     * @return the value of dis_delivery_place.dep_id
     *
     * @mbg.generated
     */
    public String getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.dep_id
     *
     * @param depId the value for dis_delivery_place.dep_id
     *
     * @mbg.generated
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.manager_id
     *
     * @return the value of dis_delivery_place.manager_id
     *
     * @mbg.generated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.manager_id
     *
     * @param managerId the value for dis_delivery_place.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.dep_name
     *
     * @return the value of dis_delivery_place.dep_name
     *
     * @mbg.generated
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.dep_name
     *
     * @param depName the value for dis_delivery_place.dep_name
     *
     * @mbg.generated
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.province_name
     *
     * @return the value of dis_delivery_place.province_name
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.province_name
     *
     * @param provinceName the value for dis_delivery_place.province_name
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.city_name
     *
     * @return the value of dis_delivery_place.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.city_name
     *
     * @param cityName the value for dis_delivery_place.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.manager_name
     *
     * @return the value of dis_delivery_place.manager_name
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.manager_name
     *
     * @param managerName the value for dis_delivery_place.manager_name
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.dep_tel
     *
     * @return the value of dis_delivery_place.dep_tel
     *
     * @mbg.generated
     */
    public String getDepTel() {
        return depTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.dep_tel
     *
     * @param depTel the value for dis_delivery_place.dep_tel
     *
     * @mbg.generated
     */
    public void setDepTel(String depTel) {
        this.depTel = depTel == null ? null : depTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.dep_addr
     *
     * @return the value of dis_delivery_place.dep_addr
     *
     * @mbg.generated
     */
    public String getDepAddr() {
        return depAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.dep_addr
     *
     * @param depAddr the value for dis_delivery_place.dep_addr
     *
     * @mbg.generated
     */
    public void setDepAddr(String depAddr) {
        this.depAddr = depAddr == null ? null : depAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_place.comment
     *
     * @return the value of dis_delivery_place.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_place.comment
     *
     * @param comment the value for dis_delivery_place.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}