package com.lzx.entity;

import java.util.Date;

public class DisDeliveryReceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_receipt.delivery_receipt_id
     *
     * @mbg.generated
     */
    private String deliveryReceiptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_receipt.start_city
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_receipt.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_receipt.mid_city
     *
     * @mbg.generated
     */
    private String midCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_receipt.make_date
     *
     * @mbg.generated
     */
    private Date makeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_receipt.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_receipt.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_receipt.delivery_receipt_id
     *
     * @return the value of dis_delivery_receipt.delivery_receipt_id
     *
     * @mbg.generated
     */
    public String getDeliveryReceiptId() {
        return deliveryReceiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_receipt.delivery_receipt_id
     *
     * @param deliveryReceiptId the value for dis_delivery_receipt.delivery_receipt_id
     *
     * @mbg.generated
     */
    public void setDeliveryReceiptId(String deliveryReceiptId) {
        this.deliveryReceiptId = deliveryReceiptId == null ? null : deliveryReceiptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_receipt.start_city
     *
     * @return the value of dis_delivery_receipt.start_city
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_receipt.start_city
     *
     * @param startCity the value for dis_delivery_receipt.start_city
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_receipt.end_city
     *
     * @return the value of dis_delivery_receipt.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_receipt.end_city
     *
     * @param endCity the value for dis_delivery_receipt.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_receipt.mid_city
     *
     * @return the value of dis_delivery_receipt.mid_city
     *
     * @mbg.generated
     */
    public String getMidCity() {
        return midCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_receipt.mid_city
     *
     * @param midCity the value for dis_delivery_receipt.mid_city
     *
     * @mbg.generated
     */
    public void setMidCity(String midCity) {
        this.midCity = midCity == null ? null : midCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_receipt.make_date
     *
     * @return the value of dis_delivery_receipt.make_date
     *
     * @mbg.generated
     */
    public Date getMakeDate() {
        return makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_receipt.make_date
     *
     * @param makeDate the value for dis_delivery_receipt.make_date
     *
     * @mbg.generated
     */
    public void setMakeDate(Date makeDate) {
        this.makeDate = makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_receipt.state
     *
     * @return the value of dis_delivery_receipt.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_receipt.state
     *
     * @param state the value for dis_delivery_receipt.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_receipt.comment
     *
     * @return the value of dis_delivery_receipt.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_receipt.comment
     *
     * @param comment the value for dis_delivery_receipt.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}