package com.lzx.entity;

import java.math.BigDecimal;

public class DisDeliveryRange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_range.range_id
     *
     * @mbg.generated
     */
    private String rangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_range.dep_id
     *
     * @mbg.generated
     */
    private String depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_range.area_id
     *
     * @mbg.generated
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_range.range_name
     *
     * @mbg.generated
     */
    private String rangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_range.delivery_price
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_delivery_range.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_range.range_id
     *
     * @return the value of dis_delivery_range.range_id
     *
     * @mbg.generated
     */
    public String getRangeId() {
        return rangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_range.range_id
     *
     * @param rangeId the value for dis_delivery_range.range_id
     *
     * @mbg.generated
     */
    public void setRangeId(String rangeId) {
        this.rangeId = rangeId == null ? null : rangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_range.dep_id
     *
     * @return the value of dis_delivery_range.dep_id
     *
     * @mbg.generated
     */
    public String getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_range.dep_id
     *
     * @param depId the value for dis_delivery_range.dep_id
     *
     * @mbg.generated
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_range.area_id
     *
     * @return the value of dis_delivery_range.area_id
     *
     * @mbg.generated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_range.area_id
     *
     * @param areaId the value for dis_delivery_range.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_range.range_name
     *
     * @return the value of dis_delivery_range.range_name
     *
     * @mbg.generated
     */
    public String getRangeName() {
        return rangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_range.range_name
     *
     * @param rangeName the value for dis_delivery_range.range_name
     *
     * @mbg.generated
     */
    public void setRangeName(String rangeName) {
        this.rangeName = rangeName == null ? null : rangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_range.delivery_price
     *
     * @return the value of dis_delivery_range.delivery_price
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_range.delivery_price
     *
     * @param deliveryPrice the value for dis_delivery_range.delivery_price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_delivery_range.comment
     *
     * @return the value of dis_delivery_range.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_delivery_range.comment
     *
     * @param comment the value for dis_delivery_range.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}