package com.lzx.entity;

public class DisManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_manager.manager_id
     *
     * @mbg.generated
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_manager.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_manager.manager_name
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_manager.manager_psd
     *
     * @mbg.generated
     */
    private String managerPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_manager.manager_sex
     *
     * @mbg.generated
     */
    private String managerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_manager.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_manager.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dis_manager.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_manager.manager_id
     *
     * @return the value of dis_manager.manager_id
     *
     * @mbg.generated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_manager.manager_id
     *
     * @param managerId the value for dis_manager.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_manager.role_id
     *
     * @return the value of dis_manager.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_manager.role_id
     *
     * @param roleId the value for dis_manager.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_manager.manager_name
     *
     * @return the value of dis_manager.manager_name
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_manager.manager_name
     *
     * @param managerName the value for dis_manager.manager_name
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_manager.manager_psd
     *
     * @return the value of dis_manager.manager_psd
     *
     * @mbg.generated
     */
    public String getManagerPsd() {
        return managerPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_manager.manager_psd
     *
     * @param managerPsd the value for dis_manager.manager_psd
     *
     * @mbg.generated
     */
    public void setManagerPsd(String managerPsd) {
        this.managerPsd = managerPsd == null ? null : managerPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_manager.manager_sex
     *
     * @return the value of dis_manager.manager_sex
     *
     * @mbg.generated
     */
    public String getManagerSex() {
        return managerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_manager.manager_sex
     *
     * @param managerSex the value for dis_manager.manager_sex
     *
     * @mbg.generated
     */
    public void setManagerSex(String managerSex) {
        this.managerSex = managerSex == null ? null : managerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_manager.tel
     *
     * @return the value of dis_manager.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_manager.tel
     *
     * @param tel the value for dis_manager.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_manager.address
     *
     * @return the value of dis_manager.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_manager.address
     *
     * @param address the value for dis_manager.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_manager.comment
     *
     * @return the value of dis_manager.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_manager.comment
     *
     * @param comment the value for dis_manager.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}