package com.lzx.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DisOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public DisOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andCarIdIsNull() {
            addCriterion("car_id is null");
            return (Criteria) this;
        }

        public Criteria andCarIdIsNotNull() {
            addCriterion("car_id is not null");
            return (Criteria) this;
        }

        public Criteria andCarIdEqualTo(String value) {
            addCriterion("car_id =", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotEqualTo(String value) {
            addCriterion("car_id <>", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdGreaterThan(String value) {
            addCriterion("car_id >", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdGreaterThanOrEqualTo(String value) {
            addCriterion("car_id >=", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLessThan(String value) {
            addCriterion("car_id <", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLessThanOrEqualTo(String value) {
            addCriterion("car_id <=", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLike(String value) {
            addCriterion("car_id like", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotLike(String value) {
            addCriterion("car_id not like", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdIn(List<String> values) {
            addCriterion("car_id in", values, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotIn(List<String> values) {
            addCriterion("car_id not in", values, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdBetween(String value1, String value2) {
            addCriterion("car_id between", value1, value2, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotBetween(String value1, String value2) {
            addCriterion("car_id not between", value1, value2, "carId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(String value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(String value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(String value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(String value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLike(String value) {
            addCriterion("customer_id like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotLike(String value) {
            addCriterion("customer_id not like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<String> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<String> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(String value1, String value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(String value1, String value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andPostPnameIsNull() {
            addCriterion("post_pname is null");
            return (Criteria) this;
        }

        public Criteria andPostPnameIsNotNull() {
            addCriterion("post_pname is not null");
            return (Criteria) this;
        }

        public Criteria andPostPnameEqualTo(String value) {
            addCriterion("post_pname =", value, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameNotEqualTo(String value) {
            addCriterion("post_pname <>", value, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameGreaterThan(String value) {
            addCriterion("post_pname >", value, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameGreaterThanOrEqualTo(String value) {
            addCriterion("post_pname >=", value, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameLessThan(String value) {
            addCriterion("post_pname <", value, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameLessThanOrEqualTo(String value) {
            addCriterion("post_pname <=", value, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameLike(String value) {
            addCriterion("post_pname like", value, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameNotLike(String value) {
            addCriterion("post_pname not like", value, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameIn(List<String> values) {
            addCriterion("post_pname in", values, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameNotIn(List<String> values) {
            addCriterion("post_pname not in", values, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameBetween(String value1, String value2) {
            addCriterion("post_pname between", value1, value2, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPnameNotBetween(String value1, String value2) {
            addCriterion("post_pname not between", value1, value2, "postPname");
            return (Criteria) this;
        }

        public Criteria andPostPtelIsNull() {
            addCriterion("post_ptel is null");
            return (Criteria) this;
        }

        public Criteria andPostPtelIsNotNull() {
            addCriterion("post_ptel is not null");
            return (Criteria) this;
        }

        public Criteria andPostPtelEqualTo(String value) {
            addCriterion("post_ptel =", value, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelNotEqualTo(String value) {
            addCriterion("post_ptel <>", value, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelGreaterThan(String value) {
            addCriterion("post_ptel >", value, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelGreaterThanOrEqualTo(String value) {
            addCriterion("post_ptel >=", value, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelLessThan(String value) {
            addCriterion("post_ptel <", value, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelLessThanOrEqualTo(String value) {
            addCriterion("post_ptel <=", value, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelLike(String value) {
            addCriterion("post_ptel like", value, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelNotLike(String value) {
            addCriterion("post_ptel not like", value, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelIn(List<String> values) {
            addCriterion("post_ptel in", values, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelNotIn(List<String> values) {
            addCriterion("post_ptel not in", values, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelBetween(String value1, String value2) {
            addCriterion("post_ptel between", value1, value2, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPtelNotBetween(String value1, String value2) {
            addCriterion("post_ptel not between", value1, value2, "postPtel");
            return (Criteria) this;
        }

        public Criteria andPostPaddrIsNull() {
            addCriterion("post_paddr is null");
            return (Criteria) this;
        }

        public Criteria andPostPaddrIsNotNull() {
            addCriterion("post_paddr is not null");
            return (Criteria) this;
        }

        public Criteria andPostPaddrEqualTo(String value) {
            addCriterion("post_paddr =", value, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrNotEqualTo(String value) {
            addCriterion("post_paddr <>", value, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrGreaterThan(String value) {
            addCriterion("post_paddr >", value, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrGreaterThanOrEqualTo(String value) {
            addCriterion("post_paddr >=", value, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrLessThan(String value) {
            addCriterion("post_paddr <", value, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrLessThanOrEqualTo(String value) {
            addCriterion("post_paddr <=", value, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrLike(String value) {
            addCriterion("post_paddr like", value, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrNotLike(String value) {
            addCriterion("post_paddr not like", value, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrIn(List<String> values) {
            addCriterion("post_paddr in", values, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrNotIn(List<String> values) {
            addCriterion("post_paddr not in", values, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrBetween(String value1, String value2) {
            addCriterion("post_paddr between", value1, value2, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andPostPaddrNotBetween(String value1, String value2) {
            addCriterion("post_paddr not between", value1, value2, "postPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPnameIsNull() {
            addCriterion("get_pname is null");
            return (Criteria) this;
        }

        public Criteria andGetPnameIsNotNull() {
            addCriterion("get_pname is not null");
            return (Criteria) this;
        }

        public Criteria andGetPnameEqualTo(String value) {
            addCriterion("get_pname =", value, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameNotEqualTo(String value) {
            addCriterion("get_pname <>", value, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameGreaterThan(String value) {
            addCriterion("get_pname >", value, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameGreaterThanOrEqualTo(String value) {
            addCriterion("get_pname >=", value, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameLessThan(String value) {
            addCriterion("get_pname <", value, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameLessThanOrEqualTo(String value) {
            addCriterion("get_pname <=", value, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameLike(String value) {
            addCriterion("get_pname like", value, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameNotLike(String value) {
            addCriterion("get_pname not like", value, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameIn(List<String> values) {
            addCriterion("get_pname in", values, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameNotIn(List<String> values) {
            addCriterion("get_pname not in", values, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameBetween(String value1, String value2) {
            addCriterion("get_pname between", value1, value2, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPnameNotBetween(String value1, String value2) {
            addCriterion("get_pname not between", value1, value2, "getPname");
            return (Criteria) this;
        }

        public Criteria andGetPtelIsNull() {
            addCriterion("get_ptel is null");
            return (Criteria) this;
        }

        public Criteria andGetPtelIsNotNull() {
            addCriterion("get_ptel is not null");
            return (Criteria) this;
        }

        public Criteria andGetPtelEqualTo(String value) {
            addCriterion("get_ptel =", value, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelNotEqualTo(String value) {
            addCriterion("get_ptel <>", value, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelGreaterThan(String value) {
            addCriterion("get_ptel >", value, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelGreaterThanOrEqualTo(String value) {
            addCriterion("get_ptel >=", value, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelLessThan(String value) {
            addCriterion("get_ptel <", value, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelLessThanOrEqualTo(String value) {
            addCriterion("get_ptel <=", value, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelLike(String value) {
            addCriterion("get_ptel like", value, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelNotLike(String value) {
            addCriterion("get_ptel not like", value, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelIn(List<String> values) {
            addCriterion("get_ptel in", values, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelNotIn(List<String> values) {
            addCriterion("get_ptel not in", values, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelBetween(String value1, String value2) {
            addCriterion("get_ptel between", value1, value2, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPtelNotBetween(String value1, String value2) {
            addCriterion("get_ptel not between", value1, value2, "getPtel");
            return (Criteria) this;
        }

        public Criteria andGetPaddrIsNull() {
            addCriterion("get_paddr is null");
            return (Criteria) this;
        }

        public Criteria andGetPaddrIsNotNull() {
            addCriterion("get_paddr is not null");
            return (Criteria) this;
        }

        public Criteria andGetPaddrEqualTo(String value) {
            addCriterion("get_paddr =", value, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrNotEqualTo(String value) {
            addCriterion("get_paddr <>", value, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrGreaterThan(String value) {
            addCriterion("get_paddr >", value, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrGreaterThanOrEqualTo(String value) {
            addCriterion("get_paddr >=", value, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrLessThan(String value) {
            addCriterion("get_paddr <", value, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrLessThanOrEqualTo(String value) {
            addCriterion("get_paddr <=", value, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrLike(String value) {
            addCriterion("get_paddr like", value, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrNotLike(String value) {
            addCriterion("get_paddr not like", value, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrIn(List<String> values) {
            addCriterion("get_paddr in", values, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrNotIn(List<String> values) {
            addCriterion("get_paddr not in", values, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrBetween(String value1, String value2) {
            addCriterion("get_paddr between", value1, value2, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGetPaddrNotBetween(String value1, String value2) {
            addCriterion("get_paddr not between", value1, value2, "getPaddr");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goods_name =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goods_name <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goods_name like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goods_name not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goods_name in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightIsNull() {
            addCriterion("goods_weight is null");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightIsNotNull() {
            addCriterion("goods_weight is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightEqualTo(Integer value) {
            addCriterion("goods_weight =", value, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightNotEqualTo(Integer value) {
            addCriterion("goods_weight <>", value, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightGreaterThan(Integer value) {
            addCriterion("goods_weight >", value, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_weight >=", value, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightLessThan(Integer value) {
            addCriterion("goods_weight <", value, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightLessThanOrEqualTo(Integer value) {
            addCriterion("goods_weight <=", value, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightIn(List<Integer> values) {
            addCriterion("goods_weight in", values, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightNotIn(List<Integer> values) {
            addCriterion("goods_weight not in", values, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightBetween(Integer value1, Integer value2) {
            addCriterion("goods_weight between", value1, value2, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andGoodsWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_weight not between", value1, value2, "goodsWeight");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("order_type like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("order_type not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNull() {
            addCriterion("order_state is null");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNotNull() {
            addCriterion("order_state is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStateEqualTo(String value) {
            addCriterion("order_state =", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotEqualTo(String value) {
            addCriterion("order_state <>", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThan(String value) {
            addCriterion("order_state >", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThanOrEqualTo(String value) {
            addCriterion("order_state >=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThan(String value) {
            addCriterion("order_state <", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThanOrEqualTo(String value) {
            addCriterion("order_state <=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLike(String value) {
            addCriterion("order_state like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotLike(String value) {
            addCriterion("order_state not like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateIn(List<String> values) {
            addCriterion("order_state in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotIn(List<String> values) {
            addCriterion("order_state not in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateBetween(String value1, String value2) {
            addCriterion("order_state between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotBetween(String value1, String value2) {
            addCriterion("order_state not between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andTransportPriceIsNull() {
            addCriterion("transport_price is null");
            return (Criteria) this;
        }

        public Criteria andTransportPriceIsNotNull() {
            addCriterion("transport_price is not null");
            return (Criteria) this;
        }

        public Criteria andTransportPriceEqualTo(BigDecimal value) {
            addCriterion("transport_price =", value, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceNotEqualTo(BigDecimal value) {
            addCriterion("transport_price <>", value, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceGreaterThan(BigDecimal value) {
            addCriterion("transport_price >", value, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("transport_price >=", value, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceLessThan(BigDecimal value) {
            addCriterion("transport_price <", value, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("transport_price <=", value, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceIn(List<BigDecimal> values) {
            addCriterion("transport_price in", values, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceNotIn(List<BigDecimal> values) {
            addCriterion("transport_price not in", values, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("transport_price between", value1, value2, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andTransportPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("transport_price not between", value1, value2, "transportPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceIsNull() {
            addCriterion("delivery_price is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceIsNotNull() {
            addCriterion("delivery_price is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceEqualTo(BigDecimal value) {
            addCriterion("delivery_price =", value, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceNotEqualTo(BigDecimal value) {
            addCriterion("delivery_price <>", value, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceGreaterThan(BigDecimal value) {
            addCriterion("delivery_price >", value, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("delivery_price >=", value, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceLessThan(BigDecimal value) {
            addCriterion("delivery_price <", value, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("delivery_price <=", value, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceIn(List<BigDecimal> values) {
            addCriterion("delivery_price in", values, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceNotIn(List<BigDecimal> values) {
            addCriterion("delivery_price not in", values, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("delivery_price between", value1, value2, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andDeliveryPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("delivery_price not between", value1, value2, "deliveryPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(String value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(String value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(String value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(String value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(String value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(String value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLike(String value) {
            addCriterion("total_price like", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotLike(String value) {
            addCriterion("total_price not like", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<String> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<String> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(String value1, String value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(String value1, String value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dis_order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}